# Generated by Django 5.0.6 on 2025-02-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_total', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertatotal',
            name='fecha',
            field=models.CharField(max_length=32),
        ),
    ]
