# Generated by Django 5.0.6 on 2025-02-06 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0004_proyectos_publicar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caudal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=5)),
                ('unidad_de_analisis', models.CharField(max_length=128)),
                ('valor', models.CharField(max_length=16)),
                ('tipo', models.CharField(max_length=16)),
                ('fech_digi', models.DateField()),
                ('hora_digi', models.TimeField()),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.RESTRICT, to='proyectos.proyectos')),
            ],
            options={
                'db_table': 'caudal',
                'unique_together': {('id_proyecto', 'fecha', 'unidad_de_analisis')},
            },
        ),
    ]
