# Generated by Django 5.0.6 on 2025-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caudal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caudal',
            name='valor',
            field=models.CharField(max_length=32),
        ),
    ]
