# Generated by Django 5.0.6 on 2025-02-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caudal', '0002_alter_caudal_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caudal',
            name='fecha',
            field=models.CharField(max_length=6),
        ),
    ]
