# Generated by Django 5.0.6 on 2025-02-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caudal', '0003_alter_caudal_fecha'),
        ('proyectos', '0004_proyectos_publicar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caudal',
            unique_together={('id_proyecto', 'fecha', 'unidad_de_analisis', 'tipo')},
        ),
    ]
