# Generated by Django 5.0.6 on 2024-08-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('fecha', models.DateTimeField()),
                ('archivo', models.FileField(max_length=255, upload_to='documentos/')),
            ],
            options={
                'db_table': 'proyectos',
            },
        ),
    ]
