# Generated by Django 5.0.6 on 2024-08-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='documentos/'),
        ),
    ]
