# Generated by Django 5.0.6 on 2024-10-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyectos_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='archivo_geo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='documentos/'),
        ),
    ]
