# Generated by Django 5.0.6 on 2024-11-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyectos_archivo_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='publicar',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
