# Generated by Django 5.0.6 on 2025-02-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_proyectos_publicar'),
        ('rendimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rendimiento',
            unique_together={('id_proyecto', 'mes', 'unidad_de_analisis', 'tipo')},
        ),
    ]
