# Generated by Django 5.0.6 on 2025-02-05 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0004_proyectos_publicar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=64)),
                ('unidad_de_analisis', models.CharField(max_length=128)),
                ('coord_x', models.IntegerField()),
                ('coord_y', models.IntegerField()),
                ('desc_info', models.CharField(max_length=255)),
                ('tendencia_qanual_medio', models.CharField(max_length=32)),
                ('tendencia_qanual_minimo', models.CharField(max_length=32)),
                ('tendencia_qanual_maximo', models.CharField(max_length=32)),
                ('usua_digi', models.CharField(max_length=12)),
                ('fech_digi', models.DateField()),
                ('hora_digi', models.TimeField()),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.RESTRICT, to='proyectos.proyectos')),
            ],
            options={
                'db_table': 'informacion',
                'unique_together': {('id_proyecto', 'zona', 'unidad_de_analisis')},
            },
        ),
    ]
