# Generated by Django 5.0.6 on 2025-02-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacion',
            name='usua_digi',
        ),
    ]
